### ISSUE TITLE
Add .NET 7 containers

### ISSUE THREAD

**Issue by stevefan1999-personal** [loft-sh/devspace-containers#11]
...and also clean up a little bit of confusing mess in the .NET section since [one of the image actually doesn't exist](https://hub.docker.com/r/loftsh/dotnet/tags?name=6.0-alpine)

**Comment by carlmontanari** [comment]
hey @stevefan1999-personal sorry for the delay here. please feel free to raise a pr here so we can get things sorted out!

**Comment by carlmontanari** [comment]
handled in #16 thank you @RyanCallahan312 !
