### ISSUE TITLE
Can we get a non-Alpine python?

### ISSUE THREAD

**Issue by dragonpaw** [loft-sh/devspace-containers#15]
For various reasons, my team prefers the Buster builds of python over the Alpine ones. (Some sample reasons: https://pythonspeed.com/articles/alpine-docker-python/)

So, any chance of a build based on the official Buster-based python-slim instead?

**Comment by carlmontanari** [comment]
Hey @dragonpaw 👋 

I don't think we'll add more images here, or at least not new distros (maybe we should be adding 3.10/3.11 images for example though). 

That said, you can of course build/host/use any images you'd like with Devspace, so you dont really "need" anything hosted here. For myself I just usually have a Dockerfile and Dockerfile.dev for every project/image and just put whatever I want/need in the Dockerfile.dev and use that for the replace image with Devspace. Would that work for ya'll? 

As an aside, my background is all python-y and I agree I never use alpine images w/ python 😁

**Comment by dragonpaw** [comment]
Fair enough. Just felt really odd for the docs to be all "We have these great containers for use with devspace, check them out" and then find that the Python ones use a flavor of OS that the official python images kinda avoid and cause a lot of bugs.

**Comment by alexandradragodan** [comment]
Hey, @dragonpaw .

Hope @carlmontanari 's reply clarified your question. 
Thanks a lot for your contribution!

Will close this issue for now. Feel free to reopen/open a new one if needed!

Have a great day!
