### ISSUE TITLE
Visual studio Remote SSH and Alpine

### ISSUE THREAD

**Issue by saberistic** [loft-sh/devspace-containers#17]
Based on link [here](https://www.devspace.sh/docs/ide-integration/visual-studio-code) VScode has issues with Alpine images and this means none of optimized dev images will work with it.

Would it be possible to add required vs libraries to optimized images?

**Comment by carlmontanari** [comment]
👋 hey @saberistic probably "no". I think generally the goal here is to have some good starting point images, not to build/maintain images for all versions/platforms/situations.

That said, you can easily use your own image of course! Something like the following would probably work (I dont know for sure, I dont use vscode):

```
FROM debian:bullseye

RUN set -x && apt-get update -y && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    ca-certificates vim && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app
```

There really isn't a lot more to the base container images than the above depending on your language/tools of choice.

**Comment by saberistic** [comment]
Hey @carlmontanari Thanks for quick reply.

Right, we relied on our own image for having VSCode work. I was just hopping to get the benefits of optimized images alongside VSCode compatibility. It's understandable if this is out of scope of work here.
