### ISSUE TITLE
Language Request: Please add support for Julia

### ISSUE THREAD

**Issue by schlichtanders** [loft-sh/devspace-containers#25]
Hello,
I today wanted to try out devspace with my julia deployment on kubernetes, however I am struggling to get started, as it is apparently not supported the same way as python / javascript for instance.

It would be great to have Julia being supported

**Comment by FabianKramm** [comment]
@schlichtanders thanks a lot for creating this issue! What exactly are you struggling with? We don't have an example but it should work very similar to other programming languages

**Comment by schlichtanders** [comment]
I was completely new and the generator initialization script was unfortuntely not very fitting for my case - asking for a dockerfile, etc. then it fallback to a generic image, where of course Julia is for sure not installed.

I was thinking that the generic image won't work with my setup, but was unsure what other image would work.

I looked further for simpler alternatives which just sync directories to kubernetes pods and am now very happy with [kubycat.io](https://www.kubycat.info/).

So if it is indeed supported to use other languages, I am sorry to not have tried enough.
