### ISSUE TITLE
devtools container images do not include devspace-restart-helper

### ISSUE THREAD

**Issue by leventogut** [loft-sh/devspace-containers#5]
The current version of DevSpace uses `dev.replacePods` by default, and the `dev.replacePods.replaceImage` is set to devtools container image of the relevant programming language. However, none of the devtools container images include `devspace-restart-helper`. Thus, current versions of devtools images can not be used for hot reloading at the moment.

This issue is to discuss and decide how to include the `devspace-restart-helper` script into devtools images.

There are two methods I can see:

* Using `injectRestartHelper: true` in `devspace.yaml` of devtools containers for each language.
  Although this option looks good, `injectRestartHelper: true` modifies the `entrypoint` / `cmd` instructions. It requires setting either `entrypoint` or `cmd,` which I do not think would be a good solution for these images.
* Modifing devtools container's Dockerfile (or in devspace.yaml using `appendDockerfileInstructions`) to fetch the `devspace-restart-helper` from devtools-containers repo.
  The drawback of this solution is that the `devspace-restart-helper` script is currently built-in to the DevSpace binary, and there would be two sources of the script.

IMHO, it would be good to move the `devspace-restart-helper` script content to the devtools-containers repo and modify the `devspace build` command to fetch from there with a local fallback. DevSpace modifications can be made at a later date, IMHO.

Additionally, the devtools-containers repo includes a `devspace_start.sh` script per language; however, the build does not include this.

**Comment by leventogut** [comment]
@FabianKramm I am happy to do the work on the DevSpace as well if you permit. Having debugged the issue I know what you use when you get the scripts from outside.

**Comment by FabianKramm** [comment]
@leventogut sure, you can work on that!
